dist: xenial
os: linux
language: python
python:
  - "3.6"
  - "3.8"

# command to install dependencies
install:
  - pip install pytest-coverage coveralls lmfit
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest --cov=brian2modelfitting

after_success:
  - if [ "$python" == "3.6" ]; then
    travis_retry coveralls;
    fi
